import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Peworld | Hire Jobs App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>
            <b>
              Welcome to <img src="/images/logo-color-primary.png" alt="" />
            </b>
          </h1>
          <h3 className="mt-5">
            Login as
            <span
              className={`ms-2 me-2 ${styles.link}`}
              onClick={() => router.replace("/auth/recruiter/login")}
            >
              Recruiter
            </span>
            or<span className={`ms-2 ${styles.link}`}>Developer</span>
          </h3>
        </div>
      </main>
    </>
  );
}
