import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Peworld | Hire Jobs App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="d-flex justify-content-center">
          <div>
            <h1>
              <b>
                Selamat Datang di
                <img
                  src="/images/logo-color-primary.png"
                  alt=""
                  className="ms-3"
                />
              </b>
            </h1>
            <h3 className="mt-5">
              Daftar Sebagai
              <span
                className={`ms-2 me-2 ${styles.link}`}
                onClick={() => router.push("/auth/recruiter/register")}
              >
                Recruiter
              </span>
              atau
              <span
                className={`ms-2 ${styles.link}`}
                onClick={() => router.push("/auth/jobseeker/register")}
              >
                Developer
              </span>
            </h3>
          </div>
        </div>
      </main>
    </>
  );
}
